services:
  frontend:
    build: .
    container_name: talent-metrics-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app # Mapea TODO (incluyendo tus node_modules locales) a /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
